version: '3'

services:
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    links:
      - db
      - redis
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    tty: true
    stdin_open: true
  db:
    image: postgres:9.6-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:4.0-alpine
    ports:
      - 6379:6379
    command: redis-server
    volumes:
      - redis-data:/data
volumes:
  bundle:
  postgres-data:
  redis-data:
